### ISSUE TITLE
Minor source change for fuerte compile

### ISSUE THREAD

**Issue by chadrockey** [rosjava/android_core#110]
_Original author: jamu...@gmail.com (April 26, 2012 03:36:09)_

Try to compile rosjava_core when you have started a fuerte install with the classic ./gradlew install and you get:

:apache_xmlrpc_common:compileJava UP-TO-DATE
:apache_xmlrpc_common:processResources UP-TO-DATE
:apache_xmlrpc_common:classes UP-TO-DATE
:apache_xmlrpc_common:jar
:apache_xmlrpc_client:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:apache_xmlrpc_client:processResources UP-TO-DATE
:apache_xmlrpc_client:classes
:apache_xmlrpc_client:jar
:apache_xmlrpc_client:install
:apache_xmlrpc_common:install
:apache_xmlrpc_server:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:apache_xmlrpc_server:processResources UP-TO-DATE
:apache_xmlrpc_server:classes
:apache_xmlrpc_server:jar
:apache_xmlrpc_server:install
:docs:copySphinxConf UP-TO-DATE
:rosjava_bootstrap:compileJava
Note: /home/jamuraa/ros_android/rosjava_core/rosjava_bootstrap/src/main/java/org/ros/internal/message/MessageImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:rosjava_bootstrap:processResources UP-TO-DATE
:rosjava_bootstrap:classes
:rosjava_bootstrap:jar
:rosjava_messages:generateSources
Exception in thread &quot;main&quot; java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:72)
    at org.ros.internal.message.StringFileProvider.addDirectory(StringFileProvider.java:112)
    at org.ros.internal.message.MessageDefinitionFileProvider.addDirectory(MessageDefinitionFileProvider.java:90)
    at org.ros.internal.message.GenerateInterfaces.generate(GenerateInterfaces.java:162)
    at org.ros.internal.message.GenerateInterfaces.main(GenerateInterfaces.java:187)

This is because of /opt/ros/fuerte/stacks being in the ROS_PACKAGE_PATH, but not existing on the default install.  That's not really a fatal error, so you should be able to just skip package directories that don't exist in the path. 

The attached patch (against tip) ignores missing paths, with a warning.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=110_

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on April 26, 2012 11:01:39_
This issue was closed by revision e24608391c59.
