### ISSUE TITLE
image_transport: NullPointerException - Key ROS_MASTER_URI expected String but value was a java.net.URI.

### ISSUE THREAD

**Issue by chadrockey** [rosjava/android_core#12]
_Original author: syss...@gmail.com (June 16, 2011 10:18:39)_

<b>What steps will reproduce the problem?</b>
1. Start tutorials/image_transport 
2. Setup an arbitrary ROS_MASTER_URI
3. Press OK -&gt; Crash

<b>What is the expected output? What do you see instead?</b>

A connection to my ros core. 

<b>What version of the product are you using? On what operating system?</b>

Android 2.3.3 on HTC Desire Z.

<b>Please provide any additional information below.</b>

W/Bundle  (15937): Key ROS_MASTER_URI expected String but value was a java.net.URI.  The default value &lt;null&gt; was returned.
W/Bundle  (15937): Attempt to cast generated internal exception:
W/Bundle  (15937): java.lang.ClassCastException: java.net.URI
W/Bundle  (15937):      at android.os.Bundle.getString(Bundle.java:1040)
W/Bundle  (15937):      at android.content.Intent.getStringExtra(Intent.java:3415)
W/Bundle  (15937):      at org.ros.tutorials.image_transport.MainActivity.onActivityResult(MainActivity.java:86)
W/Bundle  (15937):      at android.app.Activity.dispatchActivityResult(Activity.java:3908)
W/Bundle  (15937):      at android.app.ActivityThread.deliverResults(ActivityThread.java:2649)
W/Bundle  (15937):      at android.app.ActivityThread.handleSendResult(ActivityThread.java:2695)
W/Bundle  (15937):      at android.app.ActivityThread.access$2000(ActivityThread.java:123)
W/Bundle  (15937):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:969)
W/Bundle  (15937):      at android.os.Handler.dispatchMessage(Handler.java:99)
W/Bundle  (15937):      at android.os.Looper.loop(Looper.java:123)
W/Bundle  (15937):      at android.app.ActivityThread.main(ActivityThread.java:3835)
W/Bundle  (15937):      at java.lang.reflect.Method.invokeNative(Native Method)
W/Bundle  (15937):      at java.lang.reflect.Method.invoke(Method.java:507)
W/Bundle  (15937):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
W/Bundle  (15937):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
W/Bundle  (15937):      at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime(15937): Shutting down VM
W/dalvikvm(15937): threadid=1: thread exiting with uncaught exception (group=0x40015560)
E/AndroidRuntime(15937): FATAL EXCEPTION: main
E/AndroidRuntime(15937): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { (has extras) }} to activity {org.ros.tutorials.image_transport/org.ros.tutorials.image_transport.MainActivity}: java.lang.NullPointerException
E/AndroidRuntime(15937):        at android.app.ActivityThread.deliverResults(ActivityThread.java:2653)
E/AndroidRuntime(15937):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:2695)
E/AndroidRuntime(15937):        at android.app.ActivityThread.access$2000(ActivityThread.java:123)
E/AndroidRuntime(15937):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:969)
E/AndroidRuntime(15937):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15937):        at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime(15937):        at android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime(15937):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15937):        at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(15937):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
E/AndroidRuntime(15937):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
E/AndroidRuntime(15937):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(15937): Caused by: java.lang.NullPointerException
E/AndroidRuntime(15937):        at java.net.URI.parseURI(URI.java:296)
E/AndroidRuntime(15937):        at java.net.URI.&lt;init&gt;(URI.java:72)
E/AndroidRuntime(15937):        at org.ros.tutorials.image_transport.MainActivity.onActivityResult(MainActivity.java:86)
E/AndroidRuntime(15937):        at android.app.Activity.dispatchActivityResult(Activity.java:3908)
E/AndroidRuntime(15937):        at android.app.ActivityThread.deliverResults(ActivityThread.java:2649)
E/AndroidRuntime(15937):        ... 11 more
W/ActivityManager( 1318):   Force finishing activity org.ros.tutorials.image_transport/.MainActivity
W/ActivityManager( 1318): Activity pause timeout for HistoryRecord{4056fad0 org.ros.tutorials.image_transport/.MainActivity}
I/Process (15937): Sending signal. PID: 15937 SIG: 9
I/ActivityManager( 1318): Process org.ros.tutorials.image_transport (pid 15937) has died.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=12_

**Comment by chadrockey** [comment]
_From munjalde...@google.com on June 23, 2011 15:37:00_
This issue was closed by revision 21890e9b35ec.
