### ISSUE TITLE
Build failure on indigo

### ISSUE THREAD

**Issue by adamantivm** [rosjava/android_core#256]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android_benchmarks:dexRelease'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/opt/android-sdk-linux/build-tools/21.1.2/dx --dex --output /home/julian/rosjava_ws_local/src/android_core/android_benchmarks/build/intermediates/dex/release --input-list=/home/julian/rosjava_ws_local/src/android_core/android_benchmarks/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
```

Need to investigate

**Comment by adamantivm** [comment]
It was a fluke, caused by having a stale build leftover.
Solved through `git clean -dxf`
