### ISSUE TITLE
Lifecycle of RosActivity broken

### ISSUE THREAD

**Issue by chadrockey** [rosjava/android_core#73]
_Original author: syss...@gmail.com (January 07, 2012 13:54:15)_

<b>What steps will reproduce the problem?</b>
1. Start android_tutorial_teleop
2. Trigger onPause by tabbing on HOME
3. Resuming the app will crash

<b>What is the expected output? What do you see instead?</b>

A nicely resuming application. Instead i get following exception:

W/System.err( 4431): Node name collision. Existing node /android/map_view (http://192.168.1.80:40256) will be shutdown.
W/dalvikvm( 4431): threadid=11: thread exiting with uncaught exception (group=0x40219760)
E/AndroidRuntime( 4431): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime( 4431): java.lang.IllegalArgumentException: value already present: org.ros.android.views.visualization.VisualizationView@40852f90
E/AndroidRuntime( 4431):        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:115)
E/AndroidRuntime( 4431):        at com.google.common.collect.AbstractBiMap.putInBothMaps(AbstractBiMap.java:111)
E/AndroidRuntime( 4431):        at com.google.common.collect.AbstractBiMap.put(AbstractBiMap.java:96)
E/AndroidRuntime( 4431):        at com.google.common.collect.HashBiMap.put(HashBiMap.java:84)
E/AndroidRuntime( 4431):        at com.google.common.collect.Synchronized$SynchronizedMap.put(Synchronized.java:908)
E/AndroidRuntime( 4431):        at org.ros.node.DefaultNodeRunner$1.run(DefaultNodeRunner.java:103)
E/AndroidRuntime( 4431):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1081)
E/AndroidRuntime( 4431):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
E/AndroidRuntime( 4431):        at java.lang.Thread.run(Thread.java:1020)
W/ActivityManager(  285):   Force finishing activity org.ros.android.tutorial.teleop/.MainActivity
I/DefaultPublisher( 4431): Subscriber unregistered: Subscriber&lt;TopicDefinition&lt;TopicIdentifier&lt;/android/map_view/compressed_map&gt;, MessageDefinition&lt;compressed_visualization_transport_msgs/CompressedBitmap, 0b83332a0dcfc02a0d2410d819cfbbdf&gt;&gt;&gt;
E/android.os.Debug(  285): Dumpstate &gt; /data/log/dumpstate_app_error

<b>What version of the product are you using? On what operating system?</b>

Latest revision of rosjava_core 55ea7586e10b / rosjava_android d6da11da14ef.

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=73_

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on January 07, 2012 15:29:51_
This is actually because of the DefaultNodeRunner not waiting for the node to be unregistered before trying to add a new one with the same name.

However, it's not clear that nodes should be shutdown in onPause anyway since they can continue to run in the NodeRunnerService.

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on January 07, 2012 15:44:56_
Looking at this closer, there are a few problems to be addressed:
- DefaultNodeRunner needs to remove the illegal node from its map immediately and somehow track that it should not be removed later when the illegal node is unregistered.
- RosActivity should only unbindService in onDestroy, not in onPause.
- init() should only be called from onCreate or when the NodeRunnerService dies since everything will stay in memory during other lifecycle events.

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on January 09, 2012 13:28:37_
This issue was closed by revision e298ebf7e9e3.
